import type { ChatConversation } from './types';

export const mockConversations: Record<string, ChatConversation> = {
  '1': {
    id: '1',
    participantId: 'eleanor',
    participantName: 'Eleanor Pena',
    participantAvatar: 'https://i.pravatar.cc/150?img=1',
    isOnline: true,
    messages: [
      {
        id: 'm1',
        senderId: 'eleanor',
        senderName: 'Eleanor Pena',
        senderAvatar: 'https://i.pravatar.cc/150?img=1',
        content: 'Hey! Can you review the dashboard for me?',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: 'm2',
        senderId: 'eleanor',
        senderName: 'Eleanor Pena',
        senderAvatar: 'https://i.pravatar.cc/150?img=1',
        content: 'I think we need to adjust the revenue projections before tomorrow\'s meeting.',
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000 + 1 * 60 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: 'm3',
        senderId: 'current-user',
        senderName: 'You',
        senderAvatar: null,
        content: 'Sure, I\'ll check the dashboard now.',
        timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: 'm4',
        senderId: 'eleanor',
        senderName: 'Eleanor Pena',
        senderAvatar: 'https://i.pravatar.cc/150?img=1',
        content: 'It will growth is coming from.',
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: 'm5',
        senderId: 'eleanor',
        senderName: 'Eleanor Pena',
        senderAvatar: 'https://i.pravatar.cc/150?img=1',
        content: 'Thanks! Also, can you make sure the engagement stats are broken down by platform?',
        timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000 + 15 * 60 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: 'm6',
        senderId: 'current-user',
        senderName: 'You',
        senderAvatar: null,
        content: 'Got it. I\'ll add a detailed table for platform engagement and update the charts.',
        timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: 'm7',
        senderId: 'current-user',
        senderName: 'You',
        senderAvatar: null,
        content: 'Thanks!',
        timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
        isRead: true,
      },
      {
        id: 'm8',
        senderId: 'eleanor',
        senderName: 'Eleanor Pena',
        senderAvatar: 'https://i.pravatar.cc/150?img=1',
        content: 'Perfect! Can you also check the forecast section? The trends from last week should be updated.',
        timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        isRead: true,
      },
    ],
  },
};

