import type { ChatEntry } from './types';

export const mockChats: ChatEntry[] = [
  {
    id: '1',
    name: 'Eleanor Pena',
    avatar: 'https://i.pravatar.cc/150?img=1',
    isOnline: true,
    lastMessage: 'Project deadline...',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    unreadCount: 2,
    isPinned: true,
  },
  {
    id: '2',
    name: 'Jacob Jones',
    avatar: 'https://i.pravatar.cc/150?img=2',
    isOnline: true,
    lastMessage: 'Monthly report nee...',
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    unreadCount: 1,
    isPinned: true,
  },
  {
    id: '3',
    name: 'Cody Fisher',
    avatar: 'https://i.pravatar.cc/150?img=3',
    isOnline: false,
    lastMessage: 'Meeting request for...',
    timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    unreadCount: 0,
    isPinned: true,
  },
  {
    id: '4',
    name: 'Esther Howard',
    avatar: 'https://i.pravatar.cc/150?img=4',
    isOnline: true,
    lastMessage: 'Client feedback update.',
    timestamp: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    unreadCount: 5,
    isPinned: true,
  },
  {
    id: '5',
    name: 'Eleanor Pena',
    avatar: 'https://i.pravatar.cc/150?img=5',
    isOnline: true,
    lastMessage: 'Project deadline...',
    timestamp: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    unreadCount: 2,
    isPinned: false,
  },
  {
    id: '6',
    name: 'Jacob Jones',
    avatar: 'https://i.pravatar.cc/150?img=6',
    isOnline: true,
    lastMessage: 'Monthly report nee...',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 1,
    isPinned: false,
  },
  {
    id: '7',
    name: 'Cody Fisher',
    avatar: 'https://i.pravatar.cc/150?img=7',
    isOnline: false,
    lastMessage: 'Meeting request fo...',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    isPinned: false,
  },
  {
    id: '8',
    name: 'Esther Howard',
    avatar: 'https://i.pravatar.cc/150?img=8',
    isOnline: false,
    lastMessage: 'Client feedback...',
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    isPinned: false,
  },
];

