import type { Appointment } from './types';

export const mockAppointments: Appointment[] = [
  {
    id: '#APT-1',
    patientName: 'Olivia Smith',
    patientAvatar: 'https://i.pravatar.cc/150?img=1',
    doctor: 'Dr. Sarah Lee',
    department: 'Cardiology',
    dateTime: '2025-09-11 09:00 AM',
    status: 'Upcoming',
  },
  {
    id: '#APT-2',
    patientName: 'James Wilson',
    patientAvatar: 'https://i.pravatar.cc/150?img=2',
    doctor: 'Dr. Emily Clark',
    department: 'Neurology',
    dateTime: '2025-09-11 10:30 AM',
    status: 'Pending',
  },
  {
    id: '#APT-3',
    patientName: 'Sophia Johnson',
    patientAvatar: 'https://i.pravatar.cc/150?img=3',
    doctor: 'Dr. Michael Brown',
    department: 'Pediatrics',
    dateTime: '2025-09-11 11:00 AM',
    status: 'Upcoming',
  },
  {
    id: '#APT-4',
    patientName: 'Liam Martinez',
    patientAvatar: 'https://i.pravatar.cc/150?img=4',
    doctor: 'Dr. Olivia Davis',
    department: 'Dermatology',
    dateTime: '2025-09-11 01:00 PM',
    status: 'Cancelled',
  },
  {
    id: '#APT-5',
    patientName: 'Emma Thompson',
    patientAvatar: 'https://i.pravatar.cc/150?img=5',
    doctor: 'Dr. Daniel Wilson',
    department: 'Orthopedics',
    dateTime: '2025-09-11 02:30 PM',
    status: 'Upcoming',
  },
  {
    id: '#APT-6',
    patientName: 'Noah Anderson',
    patientAvatar: 'https://i.pravatar.cc/150?img=6',
    doctor: 'Dr. Sophia Moore',
    department: 'Gynecology',
    dateTime: '2025-09-11 03:00 PM',
    status: 'Upcoming',
  },
  {
    id: '#APT-7',
    patientName: 'Mason Lee',
    patientAvatar: 'https://i.pravatar.cc/150?img=7',
    doctor: 'Dr. Lucas Taylor',
    department: 'Oncology',
    dateTime: '2025-09-11 03:45 PM',
    status: 'Pending',
  },
  {
    id: '#APT-8',
    patientName: 'Ava Scott',
    patientAvatar: 'https://i.pravatar.cc/150?img=8',
    doctor: 'Dr. Benjamin White',
    department: 'Pediatrics',
    dateTime: '2025-09-11 04:15 PM',
    status: 'Upcoming',
  },
  {
    id: '#APT-9',
    patientName: 'Ethan Harris',
    patientAvatar: 'https://i.pravatar.cc/150?img=9',
    doctor: 'Dr. Charlotte King',
    department: 'Cardiology',
    dateTime: '2025-09-11 05:00 PM',
    status: 'Upcoming',
  },
  {
    id: '#APT-10',
    patientName: 'Isabella Garcia',
    patientAvatar: 'https://i.pravatar.cc/150?img=10',
    doctor: 'Dr. William Martinez',
    department: 'Dermatology',
    dateTime: '2025-09-12 09:00 AM',
    status: 'Completed',
  },
];

